vscode:
  extensions:
    - abusaidm.html-snippets@0.2.1:HrYIjYqOIABbxFB9g9kqXQ==
    - vscode.html-language-features@1.50.1:wtgosOvwmNPlqjcgbOH4ww==
    - dbaeumer.vscode-eslint@2.1.8:02aHhbJ0Q4aGdjHXlTdVKg==